# Generated by Django 4.0.2 on 2022-02-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_amount_expense_cost_dollars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date_created',
        ),
    ]
