# Generated by Django 4.0.2 on 2022-02-23 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=96)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('tag', models.CharField(blank=True, choices=[('Groceries', 'Groceries'), ('Hygiene', 'Hygiene'), ('Makeup', 'Makeup'), ('Gifts', 'Gifts'), ('Cafe', 'Cafe'), ('Restaurants', 'Restaurants'), ('Education', 'Education'), ('Other', 'Other')], max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime.today)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
