# Generated by Django 4.0.2 on 2022-02-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_expense_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
        migrations.AlterField(
            model_name='expense',
            name='cost_dollars',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tag',
            field=models.CharField(blank=True, choices=[('Groceries', 'Groceries'), ('Hygiene', 'Hygiene'), ('Makeup', 'Makeup'), ('Gifts', 'Gifts'), ('Cafe', 'Cafe'), ('Hobbies', 'Hobbies'), ('Restaurants', 'Restaurants'), ('Education', 'Education'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
