# Generated by Django 4.0.2 on 2022-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_expense_name_alter_expense_cost_dollars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(default='...', max_length=500),
        ),
    ]
